name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Create release
        run: |
          tag=$(date +%Y.%m.%d)-$GITHUB_RUN_ID
          triggered_by="🤖"
          if [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            triggered_by="✍️"
          fi

          gh release create "$tag" --title="$tag $triggered_by" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
